version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OLLAMA_HOST=ollama
      - APP_LANGUAGE=ar
      - DEBUG=false
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  # Optional: Add monitoring or logging service
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

volumes:
  ollama_data:
    driver: local
