app:
  name: "محلل المواقع | AI Web Scraper"
  version: "2.1.0"
  environment: production
  languages:
    default: ar
    available: [ar, en]
  rtl: true     # Will be dynamically set based on language

logging:
  console_level: ERROR
  file_level: INFO
  file_name: app.log
  max_file_size: 52428800  # 50MB
  backup_count: 10

scraper:
  default_timeout: 45
  headless_mode: true
  user_agent_rotation: true
  proxy_support: true
  encoding: utf-8
  max_retries: 3
  wait_time: 5

analyzer:
  model: llama3.2
  embedding_model: sentence-transformers/all-mpnet-base-v2
  chunk_size: 2000
  chunk_overlap: 400
  prompts:
    ar:
      summary: "قم بتلخيص النص التالي مع التركيز على النقاط الرئيسية:"
      technical: "قم بتحليل النص التالي من الناحية التقنية وتحديد المعلومات المهمة:"
      custom: "قم بتحليل النص التالي حسب الاستعلام المخصص:"
    en:
      summary: "Summarize the following text focusing on key points:"
      technical: "Analyze the following text technically and identify important information:"
      custom: "Analyze the following text according to the custom query:"

ui:
  theme: light
  accent_color: '#2ecc71'
  max_results_display: 250
  fonts:
    ar: 'Cairo'
    en: 'Inter'
  directions:
    ar: rtl
    en: ltr
  translations:
    ar:
      app_title: "محلل المواقع"
      settings: "الإعدادات"
      analysis: "التحليل"
      scraping: "استخراج البيانات"
      export: "تصدير"
    en:
      app_title: "AI Web Scraper"
      settings: "Settings"
      analysis: "Analysis"
      scraping: "Web Scraping"
      export: "Export"

export:
  default_format: json
  allowed_formats:
    - csv
    - json
    - excel
    - parquet
  file_encoding: utf-8
  max_rows: 100000
